### PR TITLE
include paths that start with /globalassets when matching

### PR DESCRIPTION
**Pull request by nkuebler001**

### CODE REVIEW

**Comment by vnbaaij** [comment]
Thanks for this fix. It has been implemented in package version 1.0.1

**Comment by vnbaaij** [comment]
Can you try with the nupkg added to the release here on GitHub?

**Comment by nkuebler001** [comment]
I just check the 1.0.2 package on the releases page and am not seeing the change in the package.

Is this the correct one?
https://github.com/vnbaaij/Baaijte.Optimizely.ImageSharp.Web/releases/download/V1.0.2/Baaijte.Optimizely.ImageSharp.Web.1.0.2.nupkg

**Comment by vnbaaij** [comment]
Can you please try with the v1.0.3 release

**Pull request merged**
