### PR TITLE
Include siteassets

### PR DESCRIPTION
**Pull request by nkuebler001**
Also include paths for site specific assets.

### CODE REVIEW

**Comment by vnbaaij** [comment]
Implemented in V1.0.5. Should be in the feed soon

**Comment by nkuebler001** [comment]
@vnbaaij Thanks. It looks like you updated the name of the package but not the name of the release. There are two releases named v 1.0.4 here:
https://github.com/vnbaaij/Baaijte.Optimizely.ImageSharp.Web/releases

I tried the latest from the optimizely nuget and am getting v 1.0.4
Their page is reflecting the older version as well:
https://nuget.optimizely.com/package/?id=Baaijte.Optimizely.ImageSharp.Web

**Comment by vnbaaij** [comment]
I updated the release tittle. The 1.0.5 package is in the feed now. Always takes some time to go through the release process.

**Comment by nkuebler001** [comment]
Just pulled it from the feed. Working now. Thanks!

**Pull request merged**
